## Types and Sequences

In [19]:
x = [1, 'a', 2, 'b']
type(x)

list

In [20]:
x.append(3.3)
print(x)

[1, 'a', 2, 'b', 3.3]


In [21]:
[1,2] + [3,4]

[1, 2, 3, 4]

In [22]:
[1]*3

[1, 1, 1]

In [23]:
1 in [1, 2, 3]

True

In [24]:
x = 'This is a string'
print(x[0]) #first character
print(x[0:1]) #first character, but we have explicitly set the end character
print(x[0:2]) #first two characters

T
T
Th


In [25]:
x[-1:-1]

''

In [26]:
x[-4:-2]

'ri'

In [27]:
firstname = 'Christopher'
lastname = 'Brooks'

print(firstname + ' ' + lastname)
print(firstname*3)
print('Chris' in firstname)

Christopher Brooks
ChristopherChristopherChristopher
True


In [28]:
#split 通过制定分隔符，进行分割。
firstname = 'Christopher Arthur Hansen Brooks'.split(' ')[0] # [0] selects the first element of the list
lastname = 'Christopher Arthur Hansen Brooks'.split(' ')[-1] # [-1] selects the last element of the list
print(firstname)
print(lastname)

Christopher
Brooks


In [10]:
'Chris' + str(2) + '3'

'Chris23'

In [30]:
x = {'Christopher Brooks': 'brooksch@umich.edu', 'Bill Gates': 'billg@microsoft.com'}
x['Christopher Brooks'] # Retrieve a value by using the indexing operator


'brooksch@umich.edu'

In [31]:
x['Kevyn Collins-Thompson'] = None
x

{'Bill Gates': 'billg@microsoft.com',
 'Christopher Brooks': 'brooksch@umich.edu',
 'Kevyn Collins-Thompson': None}

In [32]:
for name in x:
    print(x[name])

brooksch@umich.edu
billg@microsoft.com
None


In [33]:
for email in x.values():
    print(email)

brooksch@umich.edu
billg@microsoft.com
None


In [34]:
for name, email in x.items():
    print(name)
    print(email)

Christopher Brooks
brooksch@umich.edu
Bill Gates
billg@microsoft.com
Kevyn Collins-Thompson
None


In [35]:
x = ('Christopher', 'Brooks', 'brooksch@umich.edu')
fname, lname, email = x
print(fname)
print(lname)
print(email)

Christopher
Brooks
brooksch@umich.edu


# More on Strings

In [36]:
sales_record = {
'price': 3.24,
'num_items': 4,
'person': 'Chris'}

sales_statement = '{} bought {} item(s) at a price of {} each for a total of {}'

print(sales_statement.format(sales_record['person'],
                             sales_record['num_items'],
                             sales_record['price'],
                             sales_record['num_items']*sales_record['price']))

Chris bought 4 item(s) at a price of 3.24 each for a total of 12.96


# Reading and Writing CSV files

In [37]:
import csv
#下面一行，旨在在IPython运行时(例如notebook)中执行.在常规Python解释器中,这将是语法错误
%precision 2 

with open('mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))
    
mpg[:3] # The first three dictionaries in our list.

[OrderedDict([('', '1'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'auto(l5)'),
              ('drv', 'f'),
              ('cty', '18'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '2'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'manual(m5)'),
              ('drv', 'f'),
              ('cty', '21'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '3'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '2'),
              ('year', '2008'),
              ('cyl', '4'),
              ('trans', 'manual(m6)'),
              ('drv',

In [38]:
mpg[0].keys()

odict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])

In [39]:
sum(float(d['cty']) for d in mpg) / len(mpg)

16.86

In [40]:
cylinders = set(d['cyl'] for d in mpg)
cylinders

{'4', '5', '6', '8'}

In [41]:
CtyMpgByCyl = []

for c in cylinders: # iterate over all the cylinder levels
    summpg = 0
    cyltypecount = 0
    for d in mpg: # iterate over all dictionaries
        if d['cyl'] == c: # if the cylinder level type matches,
            summpg += float(d['cty']) # add the cty mpg
            cyltypecount += 1 # increment the count
    CtyMpgByCyl.append((c, summpg / cyltypecount)) # append the tuple ('cylinder', 'avg mpg')

CtyMpgByCyl.sort(key=lambda x: x[0])
CtyMpgByCyl

[('4', 21.01), ('5', 20.50), ('6', 16.22), ('8', 12.57)]

In [42]:
CtyMpgByCyl.sort(key=lambda x: x[1])
CtyMpgByCyl

[('8', 12.57), ('6', 16.22), ('5', 20.50), ('4', 21.01)]

# Dates and Times

In [1]:
import datetime as dt
import time as tm

In [2]:
tm.time()

1568531950.2500076

In [11]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2019, 9, 15, 16, 15, 46, 495454)

In [12]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second # get year, month, day, etc.from a datetime

(2019, 9, 15, 16, 15, 46)

In [47]:
delta = dt.timedelta(days = 100) # create a timedelta of 100 days
delta

datetime.timedelta(100)

In [48]:
today = dt.date.today()

In [49]:
today - delta # the date 100 days ago

datetime.date(2019, 6, 3)

In [50]:
today

datetime.date(2019, 9, 11)

# Objects and map()

In [51]:
store1 = [10.00, 11.00, 12.34, 2.34]
store2 = [9.00, 11.10, 12.34, 2.01]
cheapest = map(min, store1, store2)
list(cheapest)

[9.00, 11.00, 12.34, 2.01]

In [52]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    title = person.split()[0]
    lastname = person.split()[-1]
    return '{} {}'.format(title, lastname)

list(map(split_title_and_name, people)) # map() 批量处理函数

['Dr. Brooks', 'Dr. Collins-Thompson', 'Dr. Vydiswaran', 'Dr. Romero']

In [53]:
class Person:
    department = 'School of Information' #a class variable

    def set_name(self, new_name): #a method
        self.name = new_name
    def set_location(self, new_location):
        self.location = new_location

In [54]:
person = Person()
person.set_name('Christopher Brooks')
person.set_location('Ann Arbor, MI, USA')
print('{} live in {} and works in the department {}'.format(person.name, person.location, person.department))

Christopher Brooks live in Ann Arbor, MI, USA and works in the department School of Information


# Lambda and List Comprehensions

In [55]:
my_list = [number for number in range(0,10) if number % 2 == 0]
my_list

[0, 2, 4, 6, 8]

In [56]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[-1]

#option 1
for person in people:
    print(split_title_and_name(person) == (lambda x: x.split()[0] + ' ' + x.split()[-1])(person))

#option 2
list(map(split_title_and_name, people)) == list(map(lambda person: person.split()[0] + ' ' + person.split()[-1],people))

True
True
True
True


True

In [57]:
def times_tables():
    lst = []
    for i in range(10):
        for j in range (10):
            lst.append(i*j)
    return lst

times_tables() == [j*i for i in range(10) for j in range(10)] 

True

# Numerical Python (NumPy)

In [20]:
import numpy as np

In [21]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [23]:
m.shape

(2, 3)

In [48]:
n = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [51]:
n = n.reshape(5, 3) # reshape array to be 3x5
n

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [29]:
o = np.linspace(0, 4, 9) # return 9 evenly spaced values from 0 to 4
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [50]:
n.resize(5,3)
n

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [65]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [66]:
y = np.array([4, 5, 6])
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [67]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [68]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

#### Combining Arrays

In [69]:
p = np.ones([2, 3],int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [70]:
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [71]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

## Operations

In [72]:
mylist = [1, 2, 3]
x = np.array(mylist)
y = np.array([4, 5, 6])
print(x + y) # elementwise addition     [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # elementwise subtraction  [1 2 3] - [4 5 6] = [-3 -3 -3]

[5 7 9]
[-3 -3 -3]


In [73]:
x.dot(y) # dot product  1*4 + 2*5 + 3*6

32

In [74]:
z = np.array([y, y**2])
print(len(z),z) # number of rows of array

2 [[ 4  5  6]
 [16 25 36]]


In [75]:
z.shape

(2, 3)

In [76]:
z.dtype

dtype('int64')

In [77]:
z = z.astype('f')
z.dtype

dtype('float32')

In [78]:
z

array([[  4.,   5.,   6.],
       [ 16.,  25.,  36.]], dtype=float32)

## Math Functions

In [79]:
a = np.array([-4, -2, 1, 3, 5])
a.std() #标准差

3.26

In [80]:
a.argmax()  ##返回索引

4

In [81]:
a.argmin()

0

## Indexing / Slicing

In [53]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [57]:
s[-5::-2]

array([64, 36, 16,  4,  0])

In [84]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [85]:
r[-1, ::2]

array([30, 32, 34])

In [86]:
r[r > 30]

array([31, 32, 33, 34, 35])

In [87]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

## Copying Data

In [88]:
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [89]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

r has also been changed!

In [90]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [91]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

Now when r_copy is modified, r will not be changed.

In [92]:
r_copy[:] = 10
print(r_copy, '\n')
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]] 

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


### Iterating Over Arrays

In [58]:
test = np.random.randint(0, 10, (4,3))
test

array([[9, 5, 7],
       [2, 9, 3],
       [5, 9, 3],
       [1, 6, 4]])

In [94]:
for row in test:
    print(row)

[0 6 1]
[1 5 2]
[5 8 8]
[0 6 1]


In [95]:
for i in range(len(test)):
    print(test[i])

[0 6 1]
[1 5 2]
[5 8 8]
[0 6 1]


In [59]:
test2 = test**2
test2

array([[81, 25, 49],
       [ 4, 81,  9],
       [25, 81,  9],
       [ 1, 36, 16]])

In [97]:
for i, j in  zip(test, test2):
    print(i,'+',j,'=',i+j)

[0 6 1] + [ 0 36  1] = [ 0 42  2]
[1 5 2] + [ 1 25  4] = [ 2 30  6]
[5 8 8] + [25 64 64] = [30 72 72]
[0 6 1] + [ 0 36  1] = [ 0 42  2]


### 记背小结

- x.split(' ')  #通过制定分隔符，进行分割
- x.formart(x) #在string插入变量 
- with open('mpg.csv') as csvfile: #打开csv
- x.keys() #表头
- x.append(a) #列表末尾添加元素
- dt.datetime.fromtimestamp(tm.time()).year #当前年(datetime as dt, time as tm)
-  dt.timedelta(days = 100) # 100天，可与时间加减
- map(fun, iter) # 循环列表执行函数
- x.shape # x的(行, 列)
- numpy.arange(start, stop, step, dtype) #创建一个间隔为step的1维数组ndarray
- np.linspace(0, 4, 9) # 生成9个元素的等差ndarray
- n.reshape(3, 5) # 返回重排列的数组
- n.rasize(3, 5) # 直接改变数据n的排列
- np.repeat([1,2,3],3) #数组每个元素按顺序扩展到3个
- np.vstack([p, 2*p]) #对应行连接
- np.hstack([p, 2*p]) #对应列连接
- z = z.astype('f') #改变数据类型
- z.stype() #返回数据类型
- a.argmax()  #返回最大值索引
- s[-5::-2] #返回索引从-5开始-2的数
- r[-1, ::2] #返回-1行，索引从0开始+2的数
- np.random.randint(0, 10, (4,3)) #生成范围0-10的int随机数组
- zip(a,b) #把a、b打包为元组的列表，类型为zip